apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator: 
  - name: mysecurebox
    literals: 
    - password=bGludXg=
resources: 
  - create-storage.yaml
  - deploy-mysql.yaml
  - deploy-wordpress.yaml
